name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm ci
      - run: npm run test
      - run: npm run build --if-present

      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-dist
          path: ./dist

  docker:

    runs-on: ubuntu-latest

    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-dist
          path: ./dist

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t mathiasgenibrel/livecampus-nestjs:latest .

      - name: Push Docker image
        run: docker push mathiasgenibrel/livecampus-nestjs:latest

  deploy:

    runs-on: ubuntu-latest

    needs: docker

    steps:
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_KEY }}
          port: 22
          script: |
            cd /home/ec2-user/project
            docker-compose pull
            docker-compose up --force-recreate -d
